name: sqlserver
services:
- name: sqldb-job
  image: mcr.microsoft.com/mssql/server:2019-latest
  env:
  - name: SA_PASSWORD
    value: Password1!
  - name: ACCEPT_EULA
    value: 'Y'
  bindings:
  - name: http
    containerPort: 1433
    port: 21433
    connectionString: Server=${host},User ID=sa;Database=JobsDb;Password=${env:SA_PASSWORD}